#use_frameworks!
source 'git@192.168.10.52:ios/PrivatePodspec.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'GBNoData_Example' do
  pod 'GBNoData', :path => '../'

  target 'GBNoData_Tests' do
    inherit! :search_paths

    
  end
end
